### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by dickermoshe** [rzashakeri/django-audio-validator#3]
The `filetype` dependency you set set in `requirements.txt` did not specify a version.
The `filetype` package has been updated and now the mappings in `audio_type_dic` are now incorrect.
`mp3` is now mapped to `mkv` for example.
This package is now broken.

**Comment by rzashakeri** [comment]
> The `filetype` dependency you set set in `requirements.txt` did not specify a version. The `filetype` package has been updated and now the mappings in `audio_type_dic` are now incorrect. `mp3` is now mapped to `mkv` for example. This package is now broken.

thanks for report
i will fix it
For now, you can use the [file-validator](https://github.com/file-validator/file-validator) library instead of this library
